{
 "title": "AKiPS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "device", "label": "Device", "query": "mlist device *" },
   { "name": "interface", "label": "Interface", "query": "mlist interface ${device} *" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "get \"${device}\" sys SNMPv2-MIB.sysDescr"
    }
   ]
  },
  {
   "title": "IPv4 Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "get \"${device}\" sys ip4addr"
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "get \"${device}\" sys SNMPv2-MIB.sysLocation"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "series interval avg ${__timeInterval} time \"from ${__timeFrom} to ${__timeTo}\" gauge \"${device}\" /cpu.*/ HOST-RESOURCES-MIB.hrProcessorLoad"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "series interval avg ${__timeInterval} time \"from ${__timeFrom} to ${__timeTo}\" vutil \"${device}\" * HOST-RESOURCES-MIB.hrStorageUtil"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "query": "series interval avg ${__timeInterval} time \"from ${__timeFrom} to ${__timeTo}\" gauge \"${device}\" temp MIKROTIK-MIB.mtxrHlTemperature"
    }
   ]
  },
  {
   "title": "Selected Interface",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "options": { "content": "# ${interface}" },
   "targets": [
    {
     "query": "series interval total ${__timeInterval} time \"from ${__timeFrom} to ${__timeTo}\" * \"${__device}\" \"${__child}\" \"${__attribute}\""
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "get \"${device}\" \"${interface}\" IF-MIB.ifSpeed"
    }
   ]
  },
  {
   "title": "Admin Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "get \"${device}\" \"${interface}\" IF-MIB.ifAdminStatus"
    }
   ]
  },
  {
   "title": "Operational Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "get \"${device}\" \"${interface}\" IF-MIB.ifOperStatus"
    }
   ]
  },
  {
   "title": "Bytes Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "series interval total ${__timeInterval} time \"from ${__timeFrom} to ${__timeTo}\" counter \"${device}\" \"${interface}\" /IF-MIB.ifHC(In|Out)Octets/"
    }
   ]
  },
  {
   "title": "Bits Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "query": "series interval avg ${__timeInterval} time \"from ${__timeFrom} to ${__timeTo}\" ifrate \"${device}\" \"${interface}\" /IF-MIB.if(In|Out)BitRate/"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "series interval avg ${__timeInterval} time \"from ${__timeFrom} to ${__timeTo}\" ifutil \"${device}\" \"${interface}\" /IF-MIB.if(In|Out)Util/"
    }
   ]
  }
 ]
}