name: Build plugin
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with: { go-version: "^1.15.2" }
      - uses: actions/setup-node@v1
        with: { node-version: "14.x" }
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Build plugin backend
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: -v buildAll
      - name: Build plugin frontend
        run: npx grafana-toolkit plugin:ci-build
      - name: Move plugin to the CI directory
        run: npx grafana-toolkit plugin:ci-build --finish
      - env:
          GRABPL_VERSION: v0.5.16
        run: wget -O /usr/local/bin/grabpl "https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/${GRABPL_VERSION}/grabpl"
      - run: chmod +x /usr/local/bin/grabpl
      - name: Bundle the plugin
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
        run: npx grafana-toolkit plugin:ci-package
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: package
          path: ./ci/packages

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with: { name: package }
      - id: package_name
        run: |
          P="$(ls ./package/*.zip)"
          echo "::set-output name=path::${P}"
          echo "::set-output name=name::$(basename $P)"
      - id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: akips-grafana ${{ github.ref }}
          draft: ${{ contains(github.ref, 'test') }}
          prerelease: ${{ contains(github.ref, 'pre') }}
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.package_name.outputs.path }}
          asset_name: ${{ steps.package_name.outputs.name }}
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.package_name.outputs.path }}.sha1
          asset_name: ${{ steps.package_name.outputs.name }}.sha1
          asset_content_type: text/plain
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/info.json
          asset_name: info.json
          asset_content_type: application/json
